TourLive/app

- app/src/main/res/values/header_strings.xml
- app/src/main/res/values/import_strings.xml
- app/src/main/res/values/maillots_strings.xml
- app/src/main/res/values/race_strings.xml
- app/src/main/res/values/specialranking_strings.xml
- app/src/main/res/values/virtualranking_strings.xml
Created Inital Strings for Application
> Inital Strings

- app/build.gradle
- build.gradle
Initial Realm Config. Keine Tests, da dies eine Projektkonfiguration ist.
> RADIOTOUR-70 | Initial Realm Config

- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/RiderAdapter.java
Rider selection implemented
LongClick for Drag implemented, Drop needs to be done in Group Fragment
> Radiotour 75 rider selection

- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/RiderAdapter.java
Fixed error with new data import
> fixed error in coloring while adding fresh data

- app/src/main/res/layout/time_picker_dialog.xml
> RADIOTOUR-79 | Added titles for the dialogs

- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/EditItemTouchHelperCallback.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/RaceGroupAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/RaceGroupRepository.java
> RADIOTOUR | Dynamic adjustment of the racegroup type & Update view after operation

- .travis.yml
- app/src/androidTest/java/ch/hsr/sa/radiotour/RiderRepositoryInstrumentedTest.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/presenter/RiderPresenter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/presenter/interfaces/IRiderPresenter.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/interfaces/IRiderRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/RiderRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/RaceFragment.java
First Test Setup for Rider Repository
> Radiotour 83

- app/src/main/java/ch/hsr/sa/radiotour/business/presenter/RaceGroupPresenter.java
- app/src/main/java/ch/hsr/sa/radiotour/business/presenter/RiderPresenter.java
- app/src/main/java/ch/hsr/sa/radiotour/business/presenter/interfaces/IRiderPresenter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/AdapterUtilitis.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/GroupAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/LittleRaceGroupAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/ParticipantAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/RaceGroupAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/RiderEditAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/RiderListAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/RiderRaceGroupAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/interfaces/IRiderRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/models/Rider.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/RaceGroupRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/RiderRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/RaceFragment.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/RiderRaceGroupFragment.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/UnknownRiderDialogFragment.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/UnknownRiderTransferDialogFramgent.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/UnknownUserDialogFragment.java
- app/src/main/res/layout/dialog_unknownrider.xml
- app/src/main/res/layout/dialog_unknowntransfer.xml
- app/src/main/res/layout/dialog_unknownuser.xml
- app/src/main/res/layout/fragment_riderracegroup.xml
- Updating of the unknown rider to a known riders isent working at this time (will come later)
- the rest should work.
> RADIOTOUR-90 | Unknown riders

- .travis.yml
- app/src/androidTest/java/ch/hsr/sa/radiotour/RaceGroupRepositoryInstrumentedTest.java
- app/src/androidTest/java/ch/hsr/sa/radiotour/RiderStageConnectionRepositoryInstrumentedTest.java
- app/src/main/java/ch/hsr/sa/radiotour/business/presenter/RiderStageConnectionPresenter.java
- app/src/main/java/ch/hsr/sa/radiotour/business/presenter/interfaces/IRiderStageConnectionPresenter.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/interfaces/IRiderStageConnectionRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/RiderStageConnectionRepository.java
Implemented all missing tests (RaceGroup, RiderStageConnection)
> RADIOTOUR-83 | Implemented all missing tests

- app/src/main/java/ch/hsr/sa/radiotour/business/Context.java
- app/src/main/java/ch/hsr/sa/radiotour/business/presenter/RaceGroupPresenter.java
- app/src/main/java/ch/hsr/sa/radiotour/business/presenter/RiderStageConnectionPresenter.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/RaceFragment.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/RiderRaceGroupFragment.java
Singleton implementation RaceGroup / Connection
> Radiotour 97

- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/UnknownRiderTransferDialogFramgent.java
Change unknown rider to known rider is now working
> RADIOTOUR-90 | Change unknown rider to known rider is now working

- app/src/androidTest/java/ch/hsr/sa/radiotour/JudgmentRepositoryInstrumentedTest.java
- app/src/androidTest/java/ch/hsr/sa/radiotour/RewardRepositoryInstrumentedTest.java
- app/src/androidTest/java/ch/hsr/sa/radiotour/RewardRiderConnectionInstrumentedTest.java
- app/src/androidTest/java/ch/hsr/sa/radiotour/RiderRepositoryInstrumentedTest.java
- app/src/androidTest/java/ch/hsr/sa/radiotour/RiderStageConnectionRepositoryInstrumentedTest.java
- app/src/androidTest/java/ch/hsr/sa/radiotour/StageRepositoryInstrumentedTest.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/RewardRepository.java
Tests for Repositories implemented
> Radiotour 99

- app/src/main/java/ch/hsr/sa/radiotour/business/Parser.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/api/APIClient.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/ImportFragment.java
Gets wrong judgments, caused of data leak on API -> needed to implement UI
> Dynamically getting the actual stage and rewards / judgments

- .travis.yml
- build.gradle
After update plugin from 2.5 to 2.6
> Activate sonarcode again

- app/src/main/java/ch/hsr/sa/radiotour/business/presenter/RiderPresenter.java
- app/src/main/java/ch/hsr/sa/radiotour/business/presenter/interfaces/IRiderPresenter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/RiderEditAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/RiderListAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/ViewPageAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/interfaces/IRiderRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/RiderRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/activites/MainActivity.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/RaceFragment.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/RiderRaceGroupFragment.java
- app/src/main/res/values/colors.xml
First implementations due to protocol
Reset States after 10s,
Reselect Race Tab,
Strikeout non active riders
> Radiotour 109

- app/src/main/java/ch/hsr/sa/radiotour/business/Context.java
- app/src/main/java/ch/hsr/sa/radiotour/business/Parser.java
- app/src/main/java/ch/hsr/sa/radiotour/business/presenter/RiderPresenter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/LittleRaceGroupAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/MaillotsAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/RaceGroupAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/RiderEditAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/RiderListAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/ViewPageAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/api/APIClient.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/api/UrlLink.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/models/JudgmentRiderConnection.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/models/Rider.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/JudgmentRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/JudgmentRiderConnectionRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/RaceGroupRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/RewardRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/RiderRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/RiderStageConnectionRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/StageRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/ErrorDialog.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/ImportFragment.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/RaceFragment.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/RiderRaceGroupFragment.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/SpecialFragment.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/UnknownRiderDialogFragment.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/UnknownRiderTransferDialogFramgent.java
Möglichst intensiv Testen um zu bestätigen, dass keine Fehler mit dem Code Clean Up entstanden sind.
> RADIOTOUR-95 | Major Code Clean-Up

- app/src/main/java/ch/hsr/sa/radiotour/business/Parser.java
- app/src/main/java/ch/hsr/sa/radiotour/business/presenter/JudgmentPresenter.java
- app/src/main/java/ch/hsr/sa/radiotour/business/presenter/JudgmentRiderConnectionPresenter.java
- app/src/main/java/ch/hsr/sa/radiotour/business/presenter/RaceGroupPresenter.java
- app/src/main/java/ch/hsr/sa/radiotour/business/presenter/RewardPresenter.java
- app/src/main/java/ch/hsr/sa/radiotour/business/presenter/RiderPresenter.java
- app/src/main/java/ch/hsr/sa/radiotour/business/presenter/RiderStageConnectionPresenter.java
- app/src/main/java/ch/hsr/sa/radiotour/business/presenter/StagePresenter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/JudgementAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/LittleRaceGroupAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/RaceGroupAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/api/APIClient.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/JudgmentRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/JudgmentRiderConnectionRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/RaceGroupRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/RewardRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/RiderRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/RiderStageConnectionRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/StageRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/activites/MainActivity.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/ErrorDialog.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/ImportFragment.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/RaceFragment.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/RiderRaceGroupFragment.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/SpecialFragment.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/UnknownRiderDialogFragment.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/UnknownRiderTransferDialogFramgent.java
> RADITOUR-95 | Code CleanUP

- app/build.gradle
- app/src/main/java/ch/hsr/sa/radiotour/business/Context.java
- app/src/main/java/ch/hsr/sa/radiotour/business/Parser.java
- app/src/main/java/ch/hsr/sa/radiotour/business/presenter/MaillotPresenter.java
- app/src/main/java/ch/hsr/sa/radiotour/business/presenter/interfaces/IMaillotPresenter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/RiderEditAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/RiderListAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/api/APIClient.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/api/UrlLink.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/RealmModul.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/interfaces/IMaillotRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/models/Maillot.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/models/RaceGroup.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/models/Rider.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/models/Stage.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/MaillotRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/RiderRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/StageRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/ImportFragment.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/RaceFragment.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/RiderRaceGroupFragment.java
- app/src/main/res/values/colors.xml
- app/src/main/res/values/import_strings.xml
Import Maillot
Update RaceGroups Coloring
> Radiotour 105

- app/src/main/java/ch/hsr/sa/radiotour/business/Parser.java
- app/src/main/java/ch/hsr/sa/radiotour/business/presenter/RaceGroupPresenter.java
- app/src/main/java/ch/hsr/sa/radiotour/business/presenter/RiderPresenter.java
- app/src/main/java/ch/hsr/sa/radiotour/business/presenter/RiderStageConnectionPresenter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/LittleRaceGroupAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/RaceGroupAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/RiderEditAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/RiderExtendedAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/RiderListAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/ViewPageAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/RealmModul.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/activites/MainActivity.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/ImportFragment.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/MaillotsFragment.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/RaceFragment.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/RiderRaceGroupFragment.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/UnknownRiderDialogFragment.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/UnknownRiderTransferDialogFramgent.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/VirtualClassFragment.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/views/SortableVirtualClassementView.java
Display the correct time and some cleanup
> RADIOTOUR-87 | Display the correct time and some cleanup

- app/src/main/res/drawable/tab_value_shape.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/header_strings.xml
- app/src/main/res/values/import_strings.xml
- app/src/main/res/values/styles.xml
> Radiotour 101

- app/src/main/java/ch/hsr/sa/radiotour/controller/AdapterUtilitis.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/MaillotsAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/RiderBasicAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/JudgmentRiderConnectionRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/UIUtilitis.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/activites/MainActivity.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/JudgmentDetailFragment.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/MaillotsFragment.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/SpecialFragment.java
> RADIOTOUR-112 | Code Cleanup

- app/src/androidTest/java/ch/hsr/sa/radiotour/StageRepositoryInstrumentedTest.java
- app/src/main/AndroidManifest.xml
- app/src/main/java/ch/hsr/sa/radiotour/business/presenter/StagePresenter.java
- app/src/main/java/ch/hsr/sa/radiotour/business/presenter/interfaces/IStagePresenter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/RaceGroupAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/api/APIClient.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/api/UrlLink.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/interfaces/IStageRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/StageRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/activites/MainActivity.java
- app/src/main/res/values/header_strings.xml
Header Implementations
Still open
- Race Times
> Radiotour 107

- app/src/androidTest/java/ch/hsr/sa/radiotour/RaceGroupRepositoryInstrumentedTest.java
- app/src/main/java/ch/hsr/sa/radiotour/business/presenter/RaceGroupPresenter.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/interfaces/IRaceGroupRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/RaceGroupRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/activites/MainActivity.java
Still open Virtual Gap of RadioTour -> needs to be asked
> Radiotour 100

- app/src/main/java/ch/hsr/sa/radiotour/business/presenter/RaceGroupPresenter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/RiderExtendedAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/RiderListAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/activites/MainActivity.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/RiderRaceGroupFragment.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/UnknownRiderTransferDialogFramgent.java
- app/src/main/res/layout/activity_main.xml
> Radiotour 120

- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/JudgementAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/JudgmentDetailFragment.java
> RADIOTOUR-117 | Bugfixing

- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/RadioTourApplication.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/ImportFragment.java
- app/src/main/res/values/import_strings.xml
Generates a realm file out of APK which is used to enable Demo Mode
> Radiotour 122

- app/src/main/java/ch/hsr/sa/radiotour/business/presenter/MaillotPresenter.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/RiderExtendedAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/activites/MainActivity.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/ImportFragment.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/RaceFragment.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/views/SortableVirtualClassementView.java
- app/src/main/res/layout/table_cell_image.xml
Bergpreis und so kommen in einem separaten Pull Request.
> RADIOTOUR-118 | Adjustments on the Classement

- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/ImportFragment.java
- app/src/main/res/layout/fragment_import.xml
- app/src/main/res/values/import_strings.xml
Display version info inside the app
> Display version info inside the app

- app/src/main/java/ch/hsr/sa/radiotour/business/Parser.java
- app/src/main/java/ch/hsr/sa/radiotour/business/presenter/StagePresenter.java
- app/src/main/java/ch/hsr/sa/radiotour/business/presenter/interfaces/IStagePresenter.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/interfaces/IStageRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/models/Stage.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/StageRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/ImportFragment.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/RiderRaceGroupFragment.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/fragment_import.xml
- app/src/main/res/values/header_strings.xml
- app/src/main/res/values/import_strings.xml
- app/src/main/res/values/styles.xml
Merge RADIOTOUR-137 before you merge this pull request.
> RADIOTOUR-133 | Import Screen Adjustments

- app/build.gradle
- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/RaceGroupAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/ImportFragment.java
- app/src/main/res/layout/fragment_import.xml
- app/src/main/res/layout/fragment_riderracegroup.xml
- app/src/main/res/layout/layout_item_rider_in_racegroup.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/import_strings.xml
Es wäre klarer, wenn die Statusmeldungen nicht nur mit der Farbe, sondern auch mit dem Text richtig angezeigt würden. Nach «Demomodus verlassen» wird Demomodus und Satus richtig angezeigt -> Müsste eigentlich funktionieren??? Bei mir läufts auf dem Emulator
Spitzengruppe sollte keine Eingabemöglichkeit für Zeiten haben -> sollte doch gehen??? bei mir klappts im Emulator
Fahrer können nicht in vorangehende Gruppen verschoben werden (ein Fahrer aus der dahinterliegenden Gruppe kann durchaus in die voranfahrende Gruppe aufschliessen)  -> sollte doch gehen? bei mir klappts im Emulator
> Radiotour 153

- .idea/modules.xml
- app/src/main/java/ch/hsr/sa/radiotour/presentation/activites/MainActivity.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/activites/SplashActivity.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/ImportFragment.java
- app/src/main/res/layout/fragment_virtualclass.xml
- app/src/main/res/values/strings.xml
> TOURLIVE-114 | Design Changes

- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/JudgmentRiderConnectionRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/activites/MainActivity.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/ImportFragment.java
> Fixed Crasches of the app

- app/src/main/java/ch/hsr/sa/radiotour/controller/adapter/RaceGroupAdapter.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/RaceGroupRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/OnDragRaceGroupListener.java
- app/src/main/java/ch/hsr/sa/radiotour/presentation/fragments/RaceFragment.java
- app/src/main/res/layout/layout_item_racegroup.xml
- app/src/main/res/layout/layout_item_racegroup_last.xml
- app/src/main/res/values/racegroup_strings.xml
TOURLIVE-137 | Corrections on the race fragment
> TOURLIVE-137 | Corrections on the race fragment

- app/src/main/java/ch/hsr/sa/radiotour/business/Parser.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/api/APIClient.java
- app/src/main/java/ch/hsr/sa/radiotour/controller/api/PostHandler.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/JudgmentRiderConnectionRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/RaceGroupRepository.java
- app/src/main/java/ch/hsr/sa/radiotour/dataaccess/repositories/RiderStageConnectionRepository.java
Logs for RaceGroups
Logs for Rider State Changed
Logs for Judgments
> TOURLIVE 156 | APP LOGS
